spring:
  application:
    name: gateway-oauth2-client
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: ${AUTH0_CLIENT_ID}
            client-secret: ${AUTH0_CLIENT_SECRET}
            # On Auth0 Allowed Callback URL's  contains : http://localhost:8080/login/oauth2/code/auth0
            scope: openid
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_basic
        provider:
          auth0:
            issuer-uri: ${AUTH0_DOMAIN}
  cloud:
    gateway:
      mvc:
        routes:
          - id: resource
            uri: http://localhost:8090/hello-resource
            predicates:
              - Path=/hello-resource
            filters:
              - TokenRelay
oauth0:
  audience: "https://sumsumne/api" # This is an Api Audience of an application created on Auth0 . We can also use the default Auth0 management API Audience i.e https://dev-io3pdasplm3nr6jt.us.auth0.com/api/v2/

logging :
  level:
    org.springframework.security: TRACE
    org.springframework.cloud.gateway: TRACE